import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import styles from './Header.module.css'
const Header = () => {
  return (
    <header className={styles.headerContainer}>
      <h1 className={styles.title}>🔥 Fireplace Palace</h1>
    </header>
  );
};

export default function Header ;{
  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    );
  }

return (
  <footer className={styles.footer}>
    <div className={styles.colunmsContainer}>
      <div className={styles.footerColunm}>
        <p>Find us on:</p>
        <ul className={styles.footerNav}>
          {socialLinks.map((link, index) => (
            <ExternalLink key={index} href={link.href} text={link.text} className={styles.socialLink} />
          ))}
        </ul>
      </div>
      <div className={styles.footerColunm}>
        <p>Contact us:</p>
        <address>
          <a href="mailto:info@firepalace.co.uk" className={styles.emailLink}>
            info@firepalace.co.uk
          </a>
        </address>
      </div>
    </div>
  </footer>
);
};
export Footer () {

import styles from './Footer.module.css';
import ExternalLink from './ExternalLink/ExternalLink';
const Footer = () => {
const socialLinks = [
{
  href: 'https://www.facebook.com',
  text: 'Facebook',
},
{
  href: 'https://www.instagram.com',
  text: 'Instagram',
},
{
  href: 'https://www.tiktok.com',
  text: 'TikTok',
},
];
return (
  <footer className={styles.footer}>
    <div className={styles.colunmsContainer}>
      <div className={styles.footerColunm}>
        <p>Find us on:</p>
        <ul className={styles.footerNav}>
          {socialLinks.map((link, index) => (
            <ExternalLink key={index} href={link.href} text={link.text} className={styles.socialLink} />
          ))}
        </ul>
      </div>
      <div className={styles.footerColunm}>
        <p>Contact us:</p>
        <address>
          <a href="mailto:info@firepalace.co.uk" className={styles.emailLink}>
            info@firepalace.co.uk
          </a>
        </address>
      </div>
    </div>
  </footer>
);
};
}

